---
image: quay.io/okderators/ingress-node-firewall-bundle:4.15.0-2024-10-21-125813
name: ingress-node-firewall.v4.15.0-2024-10-21-125813
package: ingress-node-firewall
properties:
- type: olm.gvk
  value:
    group: ingressnodefirewall.openshift.io
    kind: IngressNodeFirewall
    version: v1alpha1
- type: olm.gvk
  value:
    group: ingressnodefirewall.openshift.io
    kind: IngressNodeFirewallConfig
    version: v1alpha1
- type: olm.gvk
  value:
    group: ingressnodefirewall.openshift.io
    kind: IngressNodeFirewallNodeState
    version: v1alpha1
- type: olm.package
  value:
    packageName: ingress-node-firewall
    version: 4.15.0-2024-10-21-125813
- type: olm.csv.metadata
  value:
    annotations:
      alm-examples: |-
        [
          {
            "apiVersion": "ingressnodefirewall.openshift.io/v1alpha1",
            "kind": "IngressNodeFirewall",
            "metadata": {
              "name": "ingressnodefirewall-demo2"
            },
            "spec": {
              "ingress": [
                {
                  "rules": [
                    {
                      "action": "Deny",
                      "order": 10,
                      "protocolConfig": {
                        "icmp": {
                          "icmpType": 8
                        },
                        "protocol": "ICMP"
                      }
                    },
                    {
                      "action": "Deny",
                      "order": 20,
                      "protocolConfig": {
                        "protocol": "TCP",
                        "tcp": {
                          "ports": "8000-9000"
                        }
                      }
                    }
                  ],
                  "sourceCIDRs": [
                    "172.16.0.0/12"
                  ]
                },
                {
                  "rules": [
                    {
                      "action": "Deny",
                      "order": 10,
                      "protocolConfig": {
                        "icmpv6": {
                          "icmpType": 128
                        },
                        "protocol": "ICMPv6"
                      }
                    }
                  ],
                  "sourceCIDRs": [
                    "fc00:f853:ccd:e793::0/64"
                  ]
                }
              ],
              "interfaces": [
                "eth0"
              ],
              "nodeSelector": {
                "matchLabels": {
                  "do-node-ingress-firewall": "true"
                }
              }
            }
          },
          {
            "apiVersion": "ingressnodefirewall.openshift.io/v1alpha1",
            "kind": "IngressNodeFirewallConfig",
            "metadata": {
              "name": "ingressnodefirewallconfig",
              "namespace": "ingress-node-firewall-system"
            },
            "spec": {
              "nodeSelector": {
                "node-role.kubernetes.io/worker": ""
              }
            }
          }
        ]
      capabilities: Basic Install
      categories: Networking
      certified: "false"
      containerImage: quay.io/okderators/ingress-node-firewall:4.15.0-2024-10-21-125813
      createdAt: "2024-10-21T13:01:31Z"
      features.operators.openshift.io/disconnected: "true"
      features.operators.openshift.io/fips-compliant: "true"
      features.operators.openshift.io/proxy-aware: "false"
      features.operators.openshift.io/tls-profiles: "false"
      features.operators.openshift.io/token-auth-aws: "false"
      features.operators.openshift.io/token-auth-azure: "false"
      features.operators.openshift.io/token-auth-gcp: "false"
      olm.skipRange: '>=4.11.0 <4.15.0'
      operatorframework.io/suggested-namespace: openshift-ingress-node-firewall
      operators.operatorframework.io/builder: operator-sdk-v1.37.0
      operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
      repository: https://github.com/openshift/ingress-node-firewall
      support: OKD Community
    apiServiceDefinitions: {}
    crdDescriptions:
      owned:
      - kind: IngressNodeFirewallConfig
        name: ingressnodefirewallconfigs.ingressnodefirewall.openshift.io
        version: v1alpha1
      - kind: IngressNodeFirewallNodeState
        name: ingressnodefirewallnodestates.ingressnodefirewall.openshift.io
        version: v1alpha1
      - kind: IngressNodeFirewall
        name: ingressnodefirewalls.ingressnodefirewall.openshift.io
        version: v1alpha1
    description: The Ingress node firewall operator, manages the configuration of
      cluster scoped Ingress Node firewall rules for Kubernetes.
    displayName: Ingress Node Firewall Operator
    installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
    keywords:
    - ingressnodefirewall
    labels:
      operatorframework.io/arch.amd64: supported
      operatorframework.io/arch.ppc64le: supported
      operatorframework.io/arch.s390x: supported
    links:
    - name: Ingress Node Firewall
      url: https://github.com/openshift/ingress-node-firewall
    maintainers:
    - email: mmahmoud@redhat.com
      name: msherif1234
    maturity: alpha
    provider:
      name: OKD Community
relatedImages:
- image: quay.io/okderators/ingress-node-firewall-bundle:4.15.0-2024-10-21-125813
  name: ""
- image: quay.io/okderators/ingress-node-firewall:4.15.0-2024-10-21-125813
  name: ""
- image: quay.io/okderators/kube-rbac-proxy:4.15
  name: ""
schema: olm.bundle
