---
schema: olm.package
name: ingress-node-firewall
defaultChannel: alpha
icon:
  base64data:
  type: image/png
---
schema: olm.channel
package: ingress-node-firewall
name: alpha
entries:
  - name: ingress-node-firewall.v4.18.0-2025-05-26-145808
    skipRange: ">=4.11.0 <4.18.0"