---
schema: olm.package
name: recipe
defaultChannel: alpha
icon:
  base64data:
  type: image/png
---
schema: olm.channel
package: recipe
name: alpha
entries:
  - name: recipe.v4.20.0-2025-10-24-154513
    skips:
      - recipe.v4.19.0-2025-09-09-141715