---
schema: olm.package
name: odf-prometheus-operator
defaultChannel: alpha
icon:
  base64data:
  type: image/png
---
schema: olm.channel
package: odf-prometheus-operator
name: alpha
entries:
  - name: odf-prometheus-operator.v4.20.0-2025-10-24-154513
    skips:
      - odf-prometheus-operator.v4.19.0-2025-09-09-141715
  - name: odf-prometheus-operator.v4.20.0-2026-02-09-114846
    replaces: odf-prometheus-operator.v4.20.0-2025-10-24-154513