---
image: quay.io/okderators/data-foundation/odf-prometheus-operator-bundle:4.18.0-2025-04-10-114854
name: odf-prometheus-operator.v4.18.0-2025-04-10-114854
package: odf-prometheus-operator
properties:
- type: olm.package
  value:
    packageName: odf-prometheus-operator
    version: 4.18.0-2025-04-10-114854
- type: olm.csv.metadata
  value:
    annotations:
      capabilities: Deep Insights
      categories: Monitoring
      certified: "false"
      containerImage: quay.io/okd/scos-content@sha256:8b5a3ed6dce833b0e42898db6e2dcdb7e6774863013c92787d2e1ffe8c147be3
      createdAt: "2024-03-01T23:43:00Z"
      description: Manage the full lifecycle of configuring and managing Prometheus
        and Alertmanager servers.
      features.operators.openshift.io/disconnected: "true"
      features.operators.openshift.io/fips-compliant: "true"
      features.operators.openshift.io/proxy-aware: "true"
      features.operators.openshift.io/tls-profiles: "false"
      features.operators.openshift.io/token-auth-aws: "false"
      features.operators.openshift.io/token-auth-azure: "false"
      features.operators.openshift.io/token-auth-gcp: "false"
      olm.skipRange: '>=4.2.0 <4.18.0-2025-04-10-114854'
      operators.operatorframework.io/operator-type: non-standalone
      repository: https://github.com/prometheus-operator/prometheus-operator
      support: OKD Community
    apiServiceDefinitions: {}
    crdDescriptions: {}
    description: |
      The Prometheus Operator for Kubernetes provides easy monitoring definitions for Kubernetes services and deployment and management of Prometheus instances.

      Once installed, the Prometheus Operator provides the following features:

      * **Create/Destroy**: Easily launch a Prometheus instance for your Kubernetes namespace, a specific application or team easily using the Operator.
      * **Simple Configuration**: Configure the fundamentals of Prometheus like versions, persistence, retention policies, and replicas from a native Kubernetes resource.
      * **Target Services via Labels**: Automatically generate monitoring target configurations based on familiar Kubernetes label queries; no need to learn a Prometheus specific configuration language.

      ### Other Supported Features

      **High availability**

      Multiple instances are run across failure zones and data is replicated. This keeps your monitoring available during an outage, when you need it most.

      **Updates via automated operations**

      New Prometheus versions are deployed using a rolling update with no downtime, making it easy to stay up to date.

      **Handles the dynamic nature of containers**

      Alerting rules are attached to groups of containers instead of individual instances, which is ideal for the highly dynamic nature of container deployment.
    displayName: Prometheus Operator
    installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
    keywords:
    - prometheus
    - monitoring
    - tsdb
    - alerting
    - observability
    labels:
      full_version: 4.18.0-2025-04-10-114854
      operatorframework.io/arch.amd64: supported
      operatorframework.io/arch.ppc64le: supported
      operatorframework.io/arch.s390x: supported
    links:
    - name: Prometheus
      url: https://www.prometheus.io/
    - name: Documentation
      url: https://github.com/prometheus-operator/prometheus-operator/tree/master/Documentation
    - name: Prometheus Operator
      url: https://github.com/prometheus-operator/prometheus-operator
    maintainers:
    - email: openshift-operators@redhat.com
      name: OKD Community
    maturity: beta
    minKubeVersion: 1.16.0
    provider:
      name: OKD Community
relatedImages:
- image: quay.io/okd/scos-content@sha256:65bd8ec0f90fdf840cf80975b31e4b99811692de8d838283664a070af1ac459a
  name: prometheus-base-image
- image: quay.io/okd/scos-content@sha256:8b5a3ed6dce833b0e42898db6e2dcdb7e6774863013c92787d2e1ffe8c147be3
  name: prometheus-operator
- image: quay.io/okd/scos-content@sha256:9d454ee0b9162e1011d8dcce85a6f44442137d5823697a897fdbf3e72e320c2f
  name: prometheus-config-reloader
- image: quay.io/okd/scos-content@sha256:fecffbec39783335dc61291204752894fd9f283f0ce740aba28fcbd260a5c2e2
  name: prometheus-alertmanager
- image: quay.io/okderators/data-foundation/odf-prometheus-operator-bundle:4.18.0-2025-04-10-114854
  name: ""
schema: olm.bundle
